## importing required libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
#loading the apple quality dataset
df = pd.read_csv('apple_quality.csv')
df

,A_id,Size,Weight,Sweetness,Crunchiness,Juiciness,Ripeness,Acidity,Quality
0,0.0,-3.970049,-2.512336,5.346330,-1.012009,1.844900,0.329840,-0.491590483,good
1,1.0,-1.195217,-2.839257,3.664059,1.588232,0.853286,0.867530,-0.722809367,good
2,2.0,-0.292024,-1.351282,-1.738429,-0.342616,2.838636,-0.038033,2.621636473,bad
3,3.0,-0.657196,-2.271627,1.324874,-0.097875,3.637970,-3.413761,0.790723217,good
4,4.0,1.364217,-1.296612,-0.384658,-0.553006,3.030874,-1.303849,0.501984036,good
...,...,...,...,...,...,...,...,...,...
3996,3996.0,-0.293118,1.949253,-0.204020,-0.640196,0.024523,-1.087900,1.854235285,good
3997,3997.0,-2.634515,-2.138247,-2.440461,0.657223,2.199709,4.763859,-1.334611391,bad
3998,3998.0,-4.008004,-1.779337,2.366397,-0.200329,2.161435,0.214488,-2.229719806,good
3999,3999.0,0.278540,-1.715505,0.121217,-1.154075,1.266677,-0.776571,1.599796456,good
4000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Created_by_Nidula_Elgiriyewithana,NaN

In [5]:
df.shape #determines the shape of the dataset

(4001, 9)

In [7]:
df.head(7) #displays first 7 rows of the dataset

,A_id,Size,Weight,Sweetness,Crunchiness,Juiciness,Ripeness,Acidity,Quality
0,0.0,-3.970049,-2.512336,5.346330,-1.012009,1.844900,0.329840,-0.491590483,good
1,1.0,-1.195217,-2.839257,3.664059,1.588232,0.853286,0.867530,-0.722809367,good
2,2.0,-0.292024,-1.351282,-1.738429,-0.342616,2.838636,-0.038033,2.621636473,bad
3,3.0,-0.657196,-2.271627,1.324874,-0.097875,3.637970,-3.413761,0.790723217,good
4,4.0,1.364217,-1.296612,-0.384658,-0.553006,3.030874,-1.303849,0.501984036,good
5,5.0,-3.425400,-1.409082,-1.913511,-0.555775,-3.853071,1.914616,-2.981523169,bad
6,6.0,1.331606,1.635956,0.875974,-1.677798,3.106344,-1.847417,2.414170509,good

In [9]:
df.tail(8) #displays last 8 rows of the dataset

,A_id,Size,Weight,Sweetness,Crunchiness,Juiciness,Ripeness,Acidity,Quality
3993,3993.0,1.520142,-0.352623,-3.206467,1.341719,0.675568,0.107093,-0.945080106,bad
3994,3994.0,1.482508,-2.581181,-0.306888,1.527877,1.056361,2.560829,-1.229254586,good
3995,3995.0,0.059386,-1.067408,-3.714549,0.473052,1.697986,2.244055,0.137784369,bad
3996,3996.0,-0.293118,1.949253,-0.204020,-0.640196,0.024523,-1.087900,1.854235285,good
3997,3997.0,-2.634515,-2.138247,-2.440461,0.657223,2.199709,4.763859,-1.334611391,bad
3998,3998.0,-4.008004,-1.779337,2.366397,-0.200329,2.161435,0.214488,-2.229719806,good
3999,3999.0,0.278540,-1.715505,0.121217,-1.154075,1.266677,-0.776571,1.599796456,good
4000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Created_by_Nidula_Elgiriyewithana,NaN

In [11]:
df.sample(10) #displays 10 rows randomly

,A_id,Size,Weight,Sweetness,Crunchiness,Juiciness,Ripeness,Acidity,Quality
1051,1051.0,2.019955,-1.486366,-2.331939,-0.396323,0.012628,-0.275645,0.019333986,bad
1724,1724.0,-0.347167,-0.710222,-0.725810,-2.185646,1.682768,-0.242841,1.934600389,good
913,913.0,-1.423471,-0.205004,-0.023427,1.218013,-3.133456,0.631300,1.367064815,bad
2158,2158.0,1.837041,-1.358521,-1.228704,2.756600,-0.909358,0.283966,0.467697195,bad
576,576.0,0.294586,-0.353755,-0.540282,2.859840,0.671990,1.291838,0.920605642,good
1157,1157.0,0.107725,1.736156,-0.756677,0.161797,-1.477468,1.782700,0.579767371,good
3144,3144.0,-2.248008,-2.310955,-0.430174,1.798926,-0.690108,0.448416,-2.872017555,bad
820,820.0,-3.382309,0.007895,-0.473654,3.608375,6.098778,-2.436305,-3.566359317,good
3876,3876.0,-2.941900,-0.677297,-1.801199,0.334617,-2.229985,1.869168,-1.331010488,bad
2605,2605.0,-0.991962,-1.709689,-1.439927,1.341055,1.250828,1.360365,3.387447604,bad

In [10]:
df.describe() #gives description of the dataset

,A_id,Size,Weight,Sweetness,Crunchiness,Juiciness,Ripeness
count,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000
mean,1999.500000,-0.503015,-0.989547,-0.470479,0.985478,0.512118,0.498277
std,1154.844867,1.928059,1.602507,1.943441,1.402757,1.930286,1.874427
min,0.000000,-7.151703,-7.149848,-6.894485,-6.055058,-5.961897,-5.864599
25%,999.750000,-1.816765,-2.011770,-1.738425,0.062764,-0.801286,-0.771677
50%,1999.500000,-0.513703,-0.984736,-0.504758,0.998249,0.534219,0.503445
75%,2999.250000,0.805526,0.030976,0.801922,1.894234,1.835976,1.766212
max,3999.000000,6.406367,5.790714,6.374916,7.619852,7.364403,7.237837

In [12]:
df.nunique() #displays no.of unique values in each and every column

A_id           4000
Size           4000
Weight         4000
Sweetness      4000
Crunchiness    4000
Juiciness      4000
Ripeness       4000
Acidity        4001
Quality           2
dtype: int64

In [14]:
df.loc[1729] #displays the data present in the 1729th index

A_id                1729.0
Size             -1.329337
Weight            0.545297
Sweetness        -1.162827
Crunchiness       2.927927
Juiciness        -1.837274
Ripeness         -1.879259
Acidity        0.051273904
Quality               good
Name: 1729, dtype: object

In [15]:
df.loc[[1,172,1729,12]] # for displaying multiple rows data in the indexes mentioned

,A_id,Size,Weight,Sweetness,Crunchiness,Juiciness,Ripeness,Acidity,Quality
1,1.0,-1.195217,-2.839257,3.664059,1.588232,0.853286,0.867530,-0.722809367,good
172,172.0,-0.125752,0.024645,0.003256,1.456974,-0.178902,2.083774,-0.131763548,good
1729,1729.0,-1.329337,0.545297,-1.162827,2.927927,-1.837274,-1.879259,0.051273904,good
12,12.0,-0.170812,-1.867271,-1.771845,2.413155,-3.094555,-0.624884,-2.076113997,bad